openapi: 3.1.0
info:
  title: API сервер для проекта «Шесть городов».
  description: |-
    * Список ресурсов и маршрутов сервера «Шесть городов».
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
  tags:
    - name: offers
      description: Действия с предложениями по аренде.
    - name: users
      description: Действия с пользователями.
    - name: comments
      description: Действия с комментариями.
