export const Component = {
  AppExceptionFilter: Symbol.for('AppExceptionFilter'),
  AuthService: Symbol.for('AuthService'),
  AuthExceptionFilter: Symbol.for('AuthExceptionFilter'),
  CommentController: Symbol.for('CommentController'),
  CommentModel: Symbol.for('CommentModel'),
  CommentService: Symbol.for('CommentService'),
  Config: Symbol.for('Config'),
  DatabaseClient: Symbol.for('DatabaseClient'),
  FavoriteModel: Symbol.for('FavoriteModel'),
  FavoriteService: Symbol.for('FavoriteService'),
  HttpExceptionFilter: Symbol.for('HttpExceptionFilter'),
  Logger: Symbol.for('Logger'),
  OfferController: Symbol.for('OfferController'),
  OfferModel: Symbol.for('OfferModel'),
  OfferService: Symbol.for('OfferService'),
  RestApplication: Symbol.for('RestApplication'),
  UserController: Symbol.for('UserController'),
  UserModel: Symbol.for('UserModel'),
  UserService: Symbol.for('UserService'),
  ValidationExceptionFilter: Symbol.for('ValidationExceptionFilter'),
} as const;
